name: magui-drupal
recipe: drupal9
config:
  webroot: web
services:
  database:
    portforward: 37001
  node:
    type: node
    globals:
      gulp-cli: "latest"
    build:
      - cd themes/custom/demo && npm install && gulp css
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node

